### ISSUE TITLE
Feature: User can view a list of players

### ISSUE THREAD

**Issue by J-Lee589** [J-Lee589/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of NBA Players.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view a list of NBA Players 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="944" alt="Screen Shot 2021-09-21 at 8 13 17 PM" src="https://user-images.githubusercontent.com/68756038/134277717-cb6e5191-761d-4b99-9991-1b9096ff9439.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add a div[data-view="players"] to the HTML.   
- [ ] Design in HTML and CSS to make app look like wireframe.
- [ ] Create a table with 8 columns.
- [ ] On the header row, add "Name", "PTS", "AST", "REB", "BLK", "STLS".
- [ ] Make a data model for each player. Each player will have firstName, lastName, playerId, stats.
- [ ] Make sure app looks good on mobile. 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
